version: '3'
services:
  settings-service-1:
    image: price-list-editor:latest
    container_name: price-list-editor
    restart: unless-stopped
    ports:
      - "****:7226"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - HTTP_PORT=7226
      - DB_SERVER=alancenter.ru
      - DB_PORT=****
      - DB_NAME=*******
      - DB_USER=******
      - DB_PASSWORD=*****
    networks:
      - temp

networks:
  temp:
    external:
      name: temp